import { useState } from 'react'
import { DEMO_MODE, fetchInsights } from '../api'
import { trackEvent } from '../analytics'
import type { AsyncState, InsightsResponse } from '../types'
import styles from './Card.module.css'
import insightStyles from './InsightsCard.module.css'

export function InsightsCard() {
  const [state, setState] = useState<AsyncState<InsightsResponse>>({
    status: 'idle',
  })

  function generate() {
    trackEvent(
      state.status === 'success' ? 'insights_regenerated' : 'insights_generated',
    )
    setState({ status: 'loading' })
    fetchInsights()
      .then((data) => setState({ status: 'success', data }))
      .catch((error: unknown) => {
        setState({
          status: 'error',
          error: error instanceof Error ? error : new Error(String(error)),
        })
      })
  }

  return (
    <section
      className={`${styles.card} ${insightStyles.insightsCard}`}
      aria-labelledby="insights-heading"
    >
      <div className={insightStyles.header}>
        <h2 id="insights-heading" className={styles.heading}>
          AI Insights
        </h2>
        <button
          type="button"
          className={insightStyles.generateButton}
          onClick={generate}
          disabled={state.status === 'loading'}
        >
          {state.status === 'success' ? 'Regenerate' : 'Generate'}
        </button>
      </div>
      <InsightsBody state={state} />
    </section>
  )
}

function InsightsBody({ state }: { state: AsyncState<InsightsResponse> }) {
  switch (state.status) {
    case 'idle':
      return (
        <p className={insightStyles.placeholder}>
          Ask Claude to analyze your current state and surface 2–3 personalized
          study insights.
        </p>
      )
    case 'loading':
      return <p className={insightStyles.placeholder}>Thinking…</p>
    case 'error':
      return (
        <p className={insightStyles.error} role="alert">
          {state.error.message}
        </p>
      )
    case 'success':
      return (
        <>
          <ul className={insightStyles.list}>
            {state.data.insights.map((insight) => (
              <li key={insight.title} className={insightStyles.item}>
                <h3 className={insightStyles.itemTitle}>{insight.title}</h3>
                <p className={insightStyles.itemBody}>{insight.body}</p>
              </li>
            ))}
          </ul>
          <p className={styles.caption}>
            Generated by {state.data.model}
            {DEMO_MODE && ' · demo data (baked response, no live Claude call)'}
          </p>
        </>
      )
    default: {
      const _exhaustive: never = state
      return _exhaustive
    }
  }
}
